ads/urls.py
from django.urls import path
from .views import UpdateAdsView
from .import views

urlpatterns = [
    path('post-ads/', views.post_ads, name='post-ads'),
    path('ads-listing/', views.ads_listing, name='ads-listing'),
    path('ads/<int:pk>/', views.ads_detail, name='ads-detail'),
    path('ads/<int:pk>/delete/', views.ads_delete, name='ads-delete'),
    path('category/<slug:slug>/', views.ads_category_archive, name='category-archive'),
    path('state/<slug:slug>/', views.ads_state_archive, name='state-archive'),
    path('city/<slug:slug>/', views.ads_city_archive, name='city-archive'),
    path('author/<int:pk>/', views.ads_author_archive, name='author-archive'),
    path('ads-search/', views.ads_search, name='ads-search'),
    path('ads-update/<int:pk>', UpdateAdsView.as_view() , name='ads-update'),
]

classifiedads/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('', include('ads.urls')),
    path('', include('profiles.urls')),
    path('', include('authentication.urls')),
]



if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

django_project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ads/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.text import slugify
from django.urls import reverse
# Default User model
from django.contrib.auth.models import User

from embed_video.fields import EmbedVideoField
#tags
from taggit.managers import TaggableManager

# Create your models here.

# Author Model
class Author(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    profile_pic = models.ImageField(default="default-profile-pic.png", upload_to='uploads/profile-pictures', null=True)

    def __str__(self):
        return self.user.username

# Ads Model
class Ads(models.Model):
    
    CONDITION = (
        ('Free', 'Free'),
        ('Paid', 'Paid'),
    )

    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=200)
    description = RichTextField()
    prize = models.DecimalField(max_digits=8, decimal_places=2)
    date_created = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('Category', on_delete=models.CASCADE, null=True) 
    entry = models.CharField(max_length=100, choices=CONDITION)
    registeration_url = models.CharField(max_length=200)
    no_of_slots = models.CharField(max_length=200)
    video = EmbedVideoField(null=True, blank=True) 
    is_featured = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    img_link= models.CharField(max_length=1000)
    tags=TaggableManager()

    class Meta:
        verbose_name_plural = "Classified Ads"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('dashboard')
      
# Category Model
class Category(models.Model):
    category_name = models.CharField(max_length=100)
    category_image = models.ImageField(upload_to='uploads/category', blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    # overriding save method to add slug field from category name if not provided
    def save(self, *args, **kwargs):
        if not self.slug and self.category_name:
            self.slug = slugify(self.category_name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.category_name

# Image Model
class AdsImages(models.Model):
    ads = models.ForeignKey(Ads, on_delete=models.CASCADE)
    #image = models.ImageField(upload_to='uploads/%Y/%m/%d', default=None)

    def __str__(self):
        return self.ads.title

    class Meta:
        verbose_name_plural = 'Classified Ads Images'

# Top Banner Model
class AdsTopBanner(models.Model):
    title = models.CharField(max_length=200, default="Place Your Ad", blank=True)
    image = models.ImageField(upload_to='banners/%Y/%m/%d', default=None)

    def __str__(self):
        return self.title

# Right Banner Model
class AdsRightBanner(models.Model):
    title = models.CharField(max_length=200, default="Place Your Ad", blank=True)
    image = models.ImageField(upload_to='banners/%Y/%m/%d', default=None)

    def __str__(self):
        return self.title

# Bottom Banner Model
class AdsBottomBanner(models.Model):
    title = models.CharField(max_length=200, default="Place Your Ad", blank=True)
    image = models.ImageField(upload_to='banners/%Y/%m/%d', default=None)

    def __str__(self):
        return self.title

    



    
    

ads/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import *

class PostAdsForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={
        'type': 'text',
        'class': 'form-control',  
        'name': 'title', 
        'placeholder': 'Title'
    }))

    description = forms.CharField(widget=CKEditorWidget(attrs={
        'type': 'text',
        'class': 'form-control',  
        'name': 'description', 
        'placeholder': 'Description'
    }))

    

    class Meta:
        model = Ads
        fields = '__all__'
        exclude = ['author', 'date_created', 'is_featured']

    

    
        

ads/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from django.db.models import Count
# Model Forms.
from .forms import PostAdsForm
from django.contrib.auth.forms import User
from django.contrib.auth.models import User
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.core.mail import send_mail

#Pagination
from django.core.paginator import Paginator

# importing messages
from django.contrib import messages

from ads.models import Author

# Create your views here.

# Post ads view
@login_required(login_url='login')
def post_ads(request):
    if request.method == 'POST':
        # Get ad title
        title = request.POST.get('title')

        # Get ad description
        description = request.POST.get('description')

        # Get ad category
        category = request.POST.get('category')
        # Check if the category exists
        category_check = Category.objects.filter(category_name=category).exists()
        if category_check:
            c = Category.objects.get(category_name=category) # Get the category if exists
        else:
            c = Category.objects.create(category_name=category) # Create the category
        
        # Get ad prize
        prize = request.POST.get('prize')
        
        # Get entry
        entry = request.POST.get('entry')
        
        

        # Get ad registeration_url
        registeration_url = request.POST.get('registeration_url')

        # Get user's phone
        phone = request.POST.get('phone')

        #Get Image URL
        img_link = request.POST.get('img_link')

        # Get ad video
        video = request.POST.get('video')

        # Get ad video
        no_of_slots = request.POST.get('no_of_slots')
        #tags
        tags = request.POST.get('tags')
        
        # Get image files length
        length = request.POST.get('length')

        # Create the ad
        ads = Ads.objects.create(author=request.user.author, title=title, description=description, prize=prize, category=c, entry=entry, no_of_slots=no_of_slots, img_link=img_link, registeration_url=registeration_url, video=video)
        


        # Attach the images with the associated ad
        #for file_num in range(0, int(length)):
         #   AdsImages.objects.create(
      #          ads=ads,
                #image=request.FILES.get(f'images{file_num}')
 #           )
        
        # Send email notificaton to Admin
        mail_subject = "New Ads submitted"
        sender_email = request.user.email
        message = f"Dear Admin, you received a new ads request from {sender_email}"
        print(message)
        to_email = settings.EMAIL_HOST_USER
        to_list = [to_email]
        from_email = settings.EMAIL_HOST_USER
        
        send_mail(
            mail_subject,
            message,
            from_email,
            to_list,
            fail_silently=False,
        )
        return render(request, 'ads/post-success.html')
        
    return render(request, 'ads/post-ads.html')

# Ads listing view
def ads_listing(request):
    ads_listing = Ads.objects.all()

    #setting up pagination

    p=Paginator(Ads.objects.all(),12)

    page = request.GET.get('page')
    ads = p.get_page(page)
    

  
    #category_listing = Category.objects.annotate(total_ads=Count('ads')).order_by('category_name')

    context = {
        #'ads_listing' : ads_listing,
        'ads':ads
      #  'category_listing' : category_listing
    }

    return render(request, 'ads/ads-listing.html', context)

# Ads detail view
def ads_detail(request, pk):
    ads_detail = get_object_or_404(Ads, pk=pk)
    ads_photos = AdsImages.objects.filter(ads=ads_detail)
    similar_posts = ads_detail.tags.similar_objects()[:5]
    
    context = {
        'ads_detail' : ads_detail,
        'similar_posts':similar_posts,
        'ads_photos' : ads_photos,
    }

    return render(request, 'ads/ads-detail.html', context)

# Ads category archive view
def ads_category_archive(request, slug):
    category = get_object_or_404(Category, slug=slug)
    ads_by_category = Ads.objects.filter(category=category)

    context = {
        'category' : category,
        'ads_by_category' : ads_by_category
    }

    return render(request, 'ads/category-archive.html', context)

# Ads state archive view
def ads_state_archive(request, slug):
    state = get_object_or_404(State, slug=slug)
    ads_by_state = Ads.objects.filter(state=state)

    context = {
        'state' : state,
        'ads_by_state' : ads_by_state
    }

    return render(request, 'ads/state-archive.html', context)

# Ads city archive view
def ads_city_archive(request, slug):
    city = get_object_or_404(City, slug=slug)
    ads_by_city = Ads.objects.filter(city=city)

    context = {
        'city' : city,
        'ads_by_city' : ads_by_city
    }

    return render(request, 'ads/city-archive.html', context)

# Ads author archive view
def ads_author_archive(request, pk):
    author = get_object_or_404(Author, pk=pk)
    total_ads = request.user.author.ads_set.all().count()
    featured_ads = request.user.author.ads_set.filter(is_featured=True).count()
    ads_by_author = Ads.objects.filter(author=author)

    p=Paginator(Ads.objects.filter(author=author),5)

    page = request.GET.get('page')
    ads_by_user = p.get_page(page)

    context = {
        'author' : author,
        'total_ads':total_ads,
        'featured_ads':featured_ads,
        'ads_by_author' : ads_by_author,
        'ads_by_user': ads_by_user
    }

    return render(request, 'ads/author-archive.html', context)

# Ads search/filter view
def ads_search(request):
    
    if request.method=="POST":
      searched=request.POST['searched']
      ads_search_result = Ads.objects.filter(title__contains=searched)
    
    #state = request.GET.get('state_name')
    #category = request.GET.get('category_name')

    #if state:
     #   ads_search_result = Ads.objects.filter(state__state_name=state)
    #elif category:
      #  ads_search_result = Ads.objects.filter(category__category_name=category)
    #else:
     #   ads_search_result = Ads.objects.filter(state__state_name=state).filter(category__category_name=category)
      
      context = {
        'searched':searched,
        'ads_search_result':ads_search_result
    }

    return render(request, 'ads/ads-search.html',context)

# Ads delete view
@login_required(login_url='login')
def ads_delete(request, pk):
    ad = get_object_or_404(Ads, pk=pk)
    ad.delete()
    return redirect("dashboard")

class UpdateAdsView(UpdateView):
  model=Ads
  #form_class=PostAdsForm
  template_name='ads/update_post.html'
  fields=['title','description','prize','category','entry','registeration_url','no_of_slots','is_active','img_link','tags']

ads/templates/ads/ads-listing1.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Page Header Start -->
<div class="page-header" style="background: url(assets/img/banner1.jpg);">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="breadcrumb-wrapper">
          <h2 class="product-title">Ads Listings</h2>
          <!-- <ol class="breadcrumb">
            <li><a href="#">Home /</a></li>
            <li class="current">Listings</li>
          </ol> -->
        </div>
      </div>
    </div>
  </div>
</div>
<!-- Page Header End -->

<!-- Main container Start -->
<div class="main-container section-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-md-12 col-xs-12 page-sidebar">
        <aside>
          <!-- Search Widget -->
          <!-- <div class="widget_search">
            <form role="search" id="search-form">
              <input type="search" class="form-control" autocomplete="off" name="s" placeholder="Search..."
                id="search-input" value="">
              <button type="submit" id="search-submit" class="search-btn"><i class="lni-search"></i></button>
            </form>
          </div> -->
          <!-- Categories Widget -->
          <div class="widget categories">
            <h4 class="widget-title">All Categories</h4>
            <ul class="categories-list">
              <li>
                {% for category in category_listing %}
                <a href="{% url 'category-archive' category.slug %}">
                  <i class="lni-folder"></i>
                  {{ category }} <span class="category-counter">({{ category.total_ads }})</span>
                </a>
                {% endfor %}
              </li>
            </ul>
          </div>
          <div class="widget">
            <h4 class="widget-title">Advertisement</h4>
            <div class="add-box">
              <img class="img-fluid" src="{% static 'img/img1.jpg' %}" alt="">
            </div>
          </div>
        </aside>
      </div>
      <div class="col-lg-8 col-md-12 col-xs-12 page-content">
        <!-- Product filter Start -->
        <!-- <div class="product-filter">
          <div class="short-name">
            <span>Showing (1 - 12 products of 7371 products)</span>
          </div>
          <div class="Show-item">
            <span>Show Items</span>
            <form class="woocommerce-ordering" method="post">
              <label>
                <select name="order" class="orderby">
                  <option selected="selected" value="menu-order">49 items</option>
                  <option value="popularity">popularity</option>
                  <option value="popularity">Average ration</option>
                  <option value="popularity">newness</option>
                  <option value="popularity">price</option>
                </select>
              </label>
            </form>
          </div>
          <ul class="nav nav-tabs">
            <li class="nav-item">
              <a class="nav-link active" data-toggle="tab" href="#grid-view"><i class="lni-grid"></i></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" data-toggle="tab" href="#list-view"><i class="lni-list"></i></a>
            </li>
          </ul>
        </div> -->
        <!-- Product filter End -->

        <!-- Adds wrapper Start -->
        <div class="adds-wrapper">
          
          <div class="tab-content">
            <div id="list-view" class="tab-pane fade active show">
              <div class="row">
                {% for ad_listing in ads_listing %}
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="featured-box">
                    <figure>
                      
                      <a href="{% url 'ads-detail' ad_listing.id %}">
                        {% for img in ad_listing.adsimages_set.all %}
                        {% if forloop.first %}
                        <img class="img-fluid" src="{{ img.image.url }}" alt="">
                        {% endif %}
                        {% endfor %}
                        
                      </a>
                    </figure>
                    <div class="feature-content">
                      <div class="product">
                        <a href="{% url 'category-archive' ad_listing.category.slug %}"><i class="lni-folder"></i> {{ ad_listing.category }}</a>
                      </div>
                      <h4><a href="{% url 'ads-detail' ad_listing.id %}">{{ ad_listing.title }}</a></h4>
                      <span>Created {{ ad_listing.date_created }}</span>
                      <ul class="address">
                        <li>
                          <i class="lni-map-marker"></i> {{ ad_listing.city }}, {{ ad_listing.state }}
                        </li>
                        <li>
                          <i class="lni-alarm-clock"></i> {{ ad_listing.date_created|date }}
                        </li>
                        <li>
                          <i class="lni-user"></i> {{ ad_listing.author.user }}
                        </li>
                        <li>
                          <i class="lni-package"></i> {{ ad_listing.condition }}
                        </li>
                      </ul>
                      <div class="listing-bottom">
                        <h3 class="price float-left">$ {{ ad_listing.price }}</h3>
                        <p class="btn-verified float-right"><i class="lni-check-box"></i>
                          Verified Ad</p>
                      </div>
                    </div>
                  </div>
                </div>
                {% endfor %}
                
              </div>
            </div>
            <!-- <div id="list-view" class="tab-pane fade">
              <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                  <div class="featured-box">
                    <figure>
                      <div class="icon">
                        <i class="lni-heart"></i>
                      </div>
                      <a href="#"><img class="img-fluid" src="{% static 'img/featured/img5.jpg' %}" alt=""></a>
                    </figure>
                    <div class="feature-content">
                      <div class="product">
                        <a href="#"><i class="lni-folder"></i> Apple</a>
                      </div>
                      <h4><a href="ads-details.html">Apple Macbook Pro 13 Inch</a></h4>
                      <span>Last Updated: 4 hours ago</span>
                      <ul class="address">
                        <li>
                          <a href="#"><i class="lni-map-marker"></i>Louis, Missouri, US</a>
                        </li>
                        <li>
                          <a href="#"><i class="lni-alarm-clock"></i> May 18, 2018</a>
                        </li>
                        <li>
                          <a href="#"><i class="lni-user"></i> Will Ernest</a>
                        </li>
                        <li>
                          <a href="#"><i class="lni-package"></i> Brand New</a>
                        </li>
                      </ul>
                      <div class="listing-bottom">
                        <h3 class="price float-left">$450.00</h3>
                        <a href="account-myads.html" class="btn-verified float-right"><i class="lni-check-box"></i>
                          Verified Ad</a>
                      </div>
                    </div>
                  </div>
                </div>
                
              </div>
            </div> -->
          </div>
          
        </div>
        <!-- Adds wrapper End -->

        <!-- Start Pagination -->
        <!-- <div class="pagination-bar">
          <nav>
            <ul class="pagination justify-content-center">
              <li class="page-item"><a class="page-link active" href="#">1</a></li>
              <li class="page-item"><a class="page-link" href="#">2</a></li>
              <li class="page-item"><a class="page-link" href="#">3</a></li>
              <li class="page-item"><a class="page-link" href="#">Next</a></li>
            </ul>
          </nav>
        </div> -->
        <!-- End Pagination -->

      </div>
    </div>
  </div>
</div>
<!-- Main container End -->

{% endblock content %}1

ads/templates/ads/ads-search1.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Latest Ads Listing Section Start -->
<section class="featured section-padding">
  <div class="container">
    
    <div class="row">
      
      {% if ads_search_result %}
        {% for ad_search in ads_search_result %}
        <div class="col-lg-12">
          <h1 class="section-title">Search Res</h1>
        </div>
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">
            <figure>
              <a href="{% url 'ads-detail' ad_search.id %}">
                  {% for img in ad_search.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>
            
            <div class="feature-content">
              <div class="product">
                  <a href="{% url 'category-archive' ad_search.category.slug %}"><i class="lni-folder"></i>{{ ad_search.category.category_name }}</a>

              </div>
              <h4><a href="{% url 'ads-detail' ad_search.id %}">{{ ad_search.title }}</a></h4>
              <span>Created: {{ ad_search.date_created }}</span>
              <ul class="address">
                <li>
                  <i class="lni-map-marker"></i>{{ ad_search.state }}
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ad_search.date_created | date }}
                </li>
                <li>
                  <i class="lni-user"></i> {{ ad_search.author.user }}
                </li>
                <li>
                  <i class="lni-package"></i>{{ ad_search.condition }}
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left">$ {{ ad_search.price }}</h3>
                <p class="btn-verified float-right"><i class="lni-check-box"></i> Verified
                  Ad</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Sorry! We didn't find any Classified Ads matching your query</h4>
          </div>
        </div>
      {% endif %}
      
    </div>
  </div>
</section>
<!-- Latest Ads Listing Section End -->


{% endblock content %}

ads/templates/ads/category-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Category Archive Section Start -->
<section class="featured section-padding">
  <div class="container">
    <h1 class="section-title">Classifieds in  <span class="focus-keyword">{{ category.category_name }}</span> category</h1>
    <div class="row">
      {% if ads_by_category %}
        {% for ads in ads_by_category %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">
            <figure>
              <a href="{% url 'ads-detail' ads.id %}">
                  {% for img in ads.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>
            <div class="feature-content">
              <h4><a href="{% url 'ads-detail' ads.id %}">{{ ads.title}}</a></h4>
              <span>Posted: {{ ads.date_created}}</span>
              <ul class="address">
                <li>
                 <i class="lni-map-marker"></i>{{ ads.state}}</a>
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ads.date_created | date}}</a>
                </li>
                <li>
                  <i class="lni-user"></i>{{ ads.author }}</a>
                </li>
                <li>
                  <i class="lni-package"></i>{{ ads.condition }}</a>
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left">$ {{ ads.price }}</h3>
                <p class="btn-verified float-right"><i class="lni-check-box"></i> Verified
                  Ad</p>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Sorry! We didn't find any Classified in this Category</h4>
          </div>
        </div>
      {% endif %}
    </div>
  </div>
</section>
<!-- Category Archive Section End -->


{% endblock content %}

ads/templates/ads/city-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- Category Archive Section Start -->
<section class="featured section-padding">
  <div class="container">
    <h1 class="section-title">Classifieds in <span class="focus-keyword">{{ city.city_name }}</span> City</h1>
    <div class="row">
      {% if ads_by_city %}
        {% for ads in ads_by_city %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">
            <figure>
              <a href="{% url 'ads-detail' ads.id %}">
                  {% for img in ads.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>
            <div class="feature-content">
              <h4><a href="{% url 'ads-detail' ads.id %}">{{ ads.title}}</a></h4>
              <span>Posted: {{ ads.date_created}}</span>
              <ul class="address">
                <li>
                  <i class="lni-map-marker"></i>{{ ads.state}}
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ads.date_created | date}}
                </li>
                <li>
                  <i class="lni-user"></i>{{ ads.author }}
                </li>
                <li>
                  <i class="lni-package"></i>{{ ads.condition }}
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left">$ {{ ads.price }}</h3>
                <p class="btn-verified float-right"><i class="lni-check-box"></i> Verified
                  Ad</p>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Sorry! We didn't find any Classified in this Category</h4>
          </div>
        </div>
      {% endif %}

      
    </div>
  </div>
</section>
<!-- Category Archive Section End -->


{% endblock content %}

ads/templates/ads/state-archive.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<!-- State Archive Section Start -->
<section class="featured section-padding">
  <div class="container">
    <h1 class="section-title">Classifieds in <span class="focus-keyword">{{ state.state_name }}</span> state</h1>
    <div class="row">
      {% if ads_by_state %}
      {% for ads in ads_by_state %}
        <div class="col-xs-6 col-sm-6 col-md-6 col-lg-4">
          <div class="featured-box">
            <figure>
              <a href="{% url 'ads-detail' ads.id %}">
                  {% for img in ads.adsimages_set.all %}
                  {% if forloop.first %}
                      <img class="img-fluid" src="{{ img.image.url }}" alt="">
                  {% endif %}
                  {% endfor %}
              </a>
            </figure>
            <div class="feature-content">
              <h4><a href="{% url 'ads-detail' ads.id %}">{{ ads.title}}</a></h4>
              <span>Posted: {{ ads.date_created}}</span>
              <ul class="address">
                <li>
                  <i class="lni-map-marker"></i>{{ ads.state}}
                </li>
                <li>
                  <i class="lni-alarm-clock"></i>{{ ads.date_created | date}}
                </li>
                <li>
                  <i class="lni-user"></i>{{ ads.author }}
                </li>
                <li>
                  <i class="lni-package"></i>{{ ads.condition }}
                </li>
              </ul>
              <div class="listing-bottom">
                <h3 class="price float-left">$ {{ ads.price }}</h3>
                <p class="btn-verified float-right"><i class="lni-check-box"></i> Verified
                  Ad</p>
              </div>
            </div>
          </div>
        </div>
      {% endfor %}
      {% else %}
        <div class="container">
          <div class="col-lg-12">
            <h4 class="text-center">Sorry! We didn't find any Classified in this Category</h4>
          </div>
        </div>
      {% endif %}    
    </div>
  </div>
</section>
<!-- State Archive Section End -->


{% endblock content %}